from Ui import UserEdit
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dtBegin = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dtBegin.setObjectName("dtBegin")
        self.horizontalLayout.addWidget(self.dtBegin)
        self.dtEnd = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dtEnd.setObjectName("dtEnd")
        self.horizontalLayout.addWidget(self.dtEnd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.twTinting = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.twTinting.setObjectName("twTinting")
        self.verticalLayout.addWidget(self.twTinting)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionInsertRecord = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Button-Add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertRecord.setIcon(icon)
        self.actionInsertRecord.setObjectName("actionInsertRecord")
        self.actionDeleteRecord = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Button-Close-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRecord.setIcon(icon1)
        self.actionDeleteRecord.setObjectName("actionDeleteRecord")
        self.actionImportProduct = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/file-import-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportProduct.setIcon(icon2)
        self.actionImportProduct.setObjectName("actionImportProduct")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/USB-Flash-Card-With-Card-Reader-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon3)
        self.actionExport.setObjectName("actionExport")
        self.actionUserEdit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/Person-Male-Light-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUserEdit.setIcon(icon4)
        self.actionUserEdit.setObjectName("actionUserEdit")
        self.actionUserChange = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/User-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUserChange.setIcon(icon5)
        self.actionUserChange.setObjectName("actionUserChange")
        self.toolBar.addAction(self.actionInsertRecord)
        self.toolBar.addAction(self.actionDeleteRecord)
        self.toolBar.addAction(self.actionImportProduct)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addAction(self.actionUserEdit)
        self.toolBar.addAction(self.actionUserChange)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionInsertRecord.setText(_translate("MainWindow", "Новая запись"))
        self.actionDeleteRecord.setText(_translate("MainWindow", "Удалить"))
        self.actionImportProduct.setText(_translate("MainWindow", "Импорт Краски"))
        self.actionExport.setText(_translate("MainWindow", "Экспорт Журнала"))
        self.actionUserEdit.setText(_translate("MainWindow", "Редактировать пользователей"))
        self.actionUserChange.setText(_translate("MainWindow", "Сменить пользователя"))
        self.actionUserChange.setToolTip(_translate("MainWindow", "Сменить пользователя"))
import Ui.resourse_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
